"""s5_usage_limits

Revision ID: 79c588f850c0
Revises: 3390b79c6d15
Create Date: 2026-05-30 23:08:00.375201
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '79c588f850c0'
down_revision: Union[str, None] = '3390b79c6d15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'subscription_usage_limits',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('plan_id', sa.Integer(), nullable=False),
        sa.Column('usage_key', sa.String(), nullable=False),
        sa.Column('limit_value', sa.Integer(), nullable=True),
        sa.Column('period', sa.String(), nullable=False, server_default='monthly'),
        sa.Column('enforcement_mode', sa.String(), nullable=False, server_default='hard'),
        sa.Column('warning_threshold_percent', sa.Integer(), nullable=False, server_default='80'),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('metadata_json', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('plan_id', 'usage_key', name='uq_subscription_usage_limits_plan_key')
    )
    op.create_index(op.f('ix_subscription_usage_limits_plan_id'), 'subscription_usage_limits', ['plan_id'], unique=False)
    op.create_index(op.f('ix_subscription_usage_limits_id'), 'subscription_usage_limits', ['id'], unique=False)

    op.create_table(
        'organization_usage_counters',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('organization_id', sa.Integer(), nullable=False),
        sa.Column('usage_key', sa.String(), nullable=False),
        sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
        sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
        sa.Column('used_value', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('last_calculated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('source', sa.String(), nullable=False, server_default='calculated'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('metadata_json', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('organization_id', 'usage_key', 'period_start', name='uq_org_usage_counters_org_key_period')
    )
    op.create_index(op.f('ix_organization_usage_counters_organization_id'), 'organization_usage_counters', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_usage_counters_id'), 'organization_usage_counters', ['id'], unique=False)

    op.create_table(
        'usage_events',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('organization_id', sa.Integer(), nullable=False),
        sa.Column('subscription_id', sa.Integer(), nullable=True),
        sa.Column('usage_key', sa.String(), nullable=False),
        sa.Column('event_type', sa.String(), nullable=False),
        sa.Column('used_value', sa.Integer(), nullable=False),
        sa.Column('limit_value', sa.Integer(), nullable=True),
        sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
        sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
        sa.Column('safe_summary', sa.String(), nullable=False),
        sa.Column('created_by_user_id', sa.Integer(), nullable=True),
        sa.Column('created_by_name', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('metadata_json', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
        sa.ForeignKeyConstraint(['subscription_id'], ['organization_subscriptions.id'], ),
        sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_events_organization_id'), 'usage_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_usage_events_id'), 'usage_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_events_id'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_organization_id'), table_name='usage_events')
    op.drop_table('usage_events')
    op.drop_index(op.f('ix_organization_usage_counters_id'), table_name='organization_usage_counters')
    op.drop_index(op.f('ix_organization_usage_counters_organization_id'), table_name='organization_usage_counters')
    op.drop_table('organization_usage_counters')
    op.drop_index(op.f('ix_subscription_usage_limits_id'), table_name='subscription_usage_limits')
    op.drop_index(op.f('ix_subscription_usage_limits_plan_id'), table_name='subscription_usage_limits')
    op.drop_table('subscription_usage_limits')
    # ### end Alembic commands ###
