"""Phase 19 CHA/customs coordination.

Revision ID: phase19_customs_coord
Revises: phase18_customer_portal
Create Date: 2026-05-28
"""
from typing import Sequence, Union
import sqlalchemy as sa
from alembic import op
from sqlalchemy import inspect

revision: str = "phase19_customs_coord"
down_revision: Union[str, None] = "phase18_customer_portal"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def _ci(n, t, c): op.execute(f"CREATE INDEX IF NOT EXISTS {n} ON {t} ({c})")

def upgrade() -> None:
    tables = set(inspect(op.get_bind()).get_table_names())
    if "customs_cases" not in tables:
        op.create_table("customs_cases", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("organization_id", sa.Integer(), sa.ForeignKey("organizations.id"), nullable=True), sa.Column("shipment_id", sa.Integer(), sa.ForeignKey("shipments.id"), nullable=False), sa.Column("case_number", sa.String(60), nullable=False, unique=True), sa.Column("customs_direction", sa.String(10), nullable=False), sa.Column("case_type", sa.String(40), nullable=False, server_default="shipping_bill"), sa.Column("status", sa.String(40), nullable=False, server_default="not_started"), sa.Column("priority", sa.String(10), nullable=False, server_default="p3"), sa.Column("cha_party_id", sa.Integer(), sa.ForeignKey("parties.id"), nullable=True), sa.Column("cha_name", sa.String(255), nullable=True), sa.Column("assigned_to_user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=True), sa.Column("assigned_to_name", sa.String(150), nullable=True), sa.Column("port_of_filing", sa.String(120), nullable=True), sa.Column("customs_location", sa.String(255), nullable=True), sa.Column("filing_mode", sa.String(40), nullable=True), sa.Column("target_filing_date", sa.DateTime(), nullable=True), sa.Column("filed_at", sa.DateTime(), nullable=True), sa.Column("cleared_at", sa.DateTime(), nullable=True), sa.Column("ooc_at", sa.DateTime(), nullable=True), sa.Column("leo_at", sa.DateTime(), nullable=True), sa.Column("created_by_user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=True), sa.Column("created_by_name", sa.String(150), nullable=True), sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=sa.func.now()), sa.Column("metadata_json", sa.JSON(), nullable=True))
    if "customs_case_milestones" not in tables:
        op.create_table("customs_case_milestones", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("customs_case_id", sa.Integer(), sa.ForeignKey("customs_cases.id"), nullable=False), sa.Column("milestone_key", sa.String(80), nullable=False), sa.Column("title", sa.String(255), nullable=False), sa.Column("status", sa.String(20), nullable=False, server_default="pending"), sa.Column("planned_at", sa.DateTime(), nullable=True), sa.Column("completed_at", sa.DateTime(), nullable=True), sa.Column("completed_by_user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=True), sa.Column("completed_by_name", sa.String(150), nullable=True), sa.Column("evidence_document_version_id", sa.Integer(), nullable=True), sa.Column("notes", sa.Text(), nullable=True), sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=sa.func.now()), sa.Column("metadata_json", sa.JSON(), nullable=True))
    if "customs_checklist_items" not in tables:
        op.create_table("customs_checklist_items", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("customs_case_id", sa.Integer(), sa.ForeignKey("customs_cases.id"), nullable=False), sa.Column("item_key", sa.String(80), nullable=False), sa.Column("title", sa.String(255), nullable=False), sa.Column("description", sa.Text(), nullable=True), sa.Column("status", sa.String(20), nullable=False, server_default="pending"), sa.Column("required", sa.Boolean(), nullable=False, server_default="true"), sa.Column("blocking", sa.Boolean(), nullable=False, server_default="false"), sa.Column("assigned_to_user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=True), sa.Column("assigned_to_name", sa.String(150), nullable=True), sa.Column("due_at", sa.DateTime(), nullable=True), sa.Column("completed_at", sa.DateTime(), nullable=True), sa.Column("completed_by_user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=True), sa.Column("completed_by_name", sa.String(150), nullable=True), sa.Column("source", sa.String(40), nullable=False, server_default="system"), sa.Column("linked_document_version_id", sa.Integer(), nullable=True), sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=sa.func.now()), sa.Column("metadata_json", sa.JSON(), nullable=True))
    if "customs_document_requirements" not in tables:
        op.create_table("customs_document_requirements", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("customs_case_id", sa.Integer(), sa.ForeignKey("customs_cases.id"), nullable=False), sa.Column("document_type", sa.String(80), nullable=False), sa.Column("required", sa.Boolean(), nullable=False, server_default="true"), sa.Column("status", sa.String(20), nullable=False, server_default="pending"), sa.Column("visible_to_customer", sa.Boolean(), nullable=False, server_default="true"), sa.Column("visible_to_cha", sa.Boolean(), nullable=False, server_default="true"), sa.Column("linked_document_version_id", sa.Integer(), nullable=True), sa.Column("required_by_role", sa.String(30), nullable=True), sa.Column("due_at", sa.DateTime(), nullable=True), sa.Column("notes", sa.Text(), nullable=True), sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=sa.func.now()), sa.Column("metadata_json", sa.JSON(), nullable=True))
    if "customs_queries" not in tables:
        op.create_table("customs_queries", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("customs_case_id", sa.Integer(), sa.ForeignKey("customs_cases.id"), nullable=False), sa.Column("shipment_id", sa.Integer(), sa.ForeignKey("shipments.id"), nullable=True), sa.Column("query_number", sa.String(60), nullable=True), sa.Column("query_type", sa.String(40), nullable=False, server_default="other"), sa.Column("source", sa.String(40), nullable=False, server_default="customs_query"), sa.Column("status", sa.String(20), nullable=False, server_default="open"), sa.Column("severity", sa.String(20), nullable=False, server_default="medium"), sa.Column("title", sa.String(500), nullable=False), sa.Column("description", sa.Text(), nullable=True), sa.Column("raised_by", sa.String(150), nullable=True), sa.Column("raised_at", sa.DateTime(), nullable=True), sa.Column("due_at", sa.DateTime(), nullable=True), sa.Column("resolved_at", sa.DateTime(), nullable=True), sa.Column("resolved_by_user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=True), sa.Column("resolved_by_name", sa.String(150), nullable=True), sa.Column("linked_exception_case_id", sa.Integer(), sa.ForeignKey("exception_cases.id"), nullable=True), sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=sa.func.now()), sa.Column("metadata_json", sa.JSON(), nullable=True))
    if "customs_query_comments" not in tables:
        op.create_table("customs_query_comments", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("customs_query_id", sa.Integer(), sa.ForeignKey("customs_queries.id"), nullable=False), sa.Column("author_type", sa.String(20), nullable=False, server_default="internal_user"), sa.Column("author_user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=True), sa.Column("author_name", sa.String(150), nullable=True), sa.Column("comment_text", sa.Text(), nullable=False), sa.Column("visible_to_customer", sa.Boolean(), nullable=False, server_default="false"), sa.Column("visible_to_cha", sa.Boolean(), nullable=False, server_default="true"), sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()), sa.Column("metadata_json", sa.JSON(), nullable=True))
    if "customs_party_assignments" not in tables:
        op.create_table("customs_party_assignments", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("customs_case_id", sa.Integer(), sa.ForeignKey("customs_cases.id"), nullable=False), sa.Column("party_id", sa.Integer(), sa.ForeignKey("parties.id"), nullable=False), sa.Column("party_role", sa.String(30), nullable=False, server_default="cha"), sa.Column("assigned_at", sa.DateTime(), nullable=False, server_default=sa.func.now()), sa.Column("assigned_by_user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=True), sa.Column("assigned_by_name", sa.String(150), nullable=True), sa.Column("status", sa.String(20), nullable=False, server_default="active"), sa.Column("notes", sa.Text(), nullable=True), sa.Column("metadata_json", sa.JSON(), nullable=True))
    if "customs_duty_records" not in tables:
        op.create_table("customs_duty_records", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("customs_case_id", sa.Integer(), sa.ForeignKey("customs_cases.id"), nullable=False), sa.Column("shipment_id", sa.Integer(), sa.ForeignKey("shipments.id"), nullable=True), sa.Column("duty_type", sa.String(40), nullable=False, server_default="basic_customs_duty"), sa.Column("currency", sa.String(10), nullable=False, server_default="INR"), sa.Column("assessed_amount", sa.Numeric(14,2), nullable=True), sa.Column("paid_amount", sa.Numeric(14,2), nullable=True), sa.Column("outstanding_amount", sa.Numeric(14,2), nullable=True), sa.Column("payment_status", sa.String(20), nullable=False, server_default="pending"), sa.Column("payment_reference", sa.String(120), nullable=True), sa.Column("paid_at", sa.DateTime(), nullable=True), sa.Column("recorded_by_user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=True), sa.Column("recorded_by_name", sa.String(150), nullable=True), sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=sa.func.now()), sa.Column("metadata_json", sa.JSON(), nullable=True))
    if "customs_reference_numbers" not in tables:
        op.create_table("customs_reference_numbers", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("customs_case_id", sa.Integer(), sa.ForeignKey("customs_cases.id"), nullable=False), sa.Column("reference_type", sa.String(40), nullable=False), sa.Column("reference_value", sa.String(255), nullable=False), sa.Column("issued_at", sa.DateTime(), nullable=True), sa.Column("source", sa.String(40), nullable=False, server_default="manual"), sa.Column("verified", sa.Boolean(), nullable=False, server_default="false"), sa.Column("verified_by_user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=True), sa.Column("verified_by_name", sa.String(150), nullable=True), sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()), sa.Column("metadata_json", sa.JSON(), nullable=True))
    if "customs_activity_logs" not in tables:
        op.create_table("customs_activity_logs", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("customs_case_id", sa.Integer(), sa.ForeignKey("customs_cases.id"), nullable=False), sa.Column("shipment_id", sa.Integer(), sa.ForeignKey("shipments.id"), nullable=True), sa.Column("activity_type", sa.String(60), nullable=False), sa.Column("safe_summary", sa.Text(), nullable=False), sa.Column("created_by_user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=True), sa.Column("created_by_name", sa.String(150), nullable=True), sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()), sa.Column("metadata_json", sa.JSON(), nullable=True))

    _ci("ix_customs_cases_shipment", "customs_cases", "shipment_id")
    _ci("ix_customs_cases_status", "customs_cases", "status")
    _ci("ix_customs_cases_direction", "customs_cases", "customs_direction")
    _ci("ix_customs_cases_number", "customs_cases", "case_number")
    _ci("ix_customs_milestones_case", "customs_case_milestones", "customs_case_id")
    _ci("ix_customs_checklist_case", "customs_checklist_items", "customs_case_id")
    _ci("ix_customs_doc_reqs_case", "customs_document_requirements", "customs_case_id")
    _ci("ix_customs_queries_case", "customs_queries", "customs_case_id")
    _ci("ix_customs_queries_status", "customs_queries", "status")
    _ci("ix_customs_query_comments_q", "customs_query_comments", "customs_query_id")
    _ci("ix_customs_party_assign_case", "customs_party_assignments", "customs_case_id")
    _ci("ix_customs_duty_case", "customs_duty_records", "customs_case_id")
    _ci("ix_customs_refs_case", "customs_reference_numbers", "customs_case_id")
    _ci("ix_customs_activity_case", "customs_activity_logs", "customs_case_id")

def downgrade() -> None:
    for t in ["customs_activity_logs", "customs_reference_numbers", "customs_duty_records", "customs_party_assignments", "customs_query_comments", "customs_queries", "customs_document_requirements", "customs_checklist_items", "customs_case_milestones", "customs_cases"]:
        op.drop_table(t)
